version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      DB_HOST: db
      DB_USER: station
      DB_PASSWORD: station
      DB_NAME: station
    depends_on:
      - db
    restart: always
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: station
      MYSQL_DATABASE: station
      MYSQL_USER: station
      MYSQL_PASSWORD: localhost
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
volumes:
  db_data: