version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      DB_HOST: db
      DB_USER: station
      DB_PASSWORD: station
      DB_NAME: station
    depends_on:
      - db
    restart: always
    networks:
      - station-network
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: station
      MYSQL_USER: station
      MYSQL_PASSWORD: station
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    networks:
      - station-network

networks:
  station-network:
volumes:
  db_data: